### ISSUE TITLE
Implement remote device control

### ISSUE THREAD

**Issue by ylevtov** [reactify/3DTI-binaural-web-demo#1]
As per Papa Sangre. Walk with thumbs pressing bottom half of the screen and rotate by swiping top half.

**Comment by ylevtov** [comment]
Actually, because we want to support being able to look up/down with the mobile device as you can with the mouse, perhaps split the screen into four sections vertically (with landscape orientation still), with the first and fourth quarters being for the footsteps, and the centre two quarters being a large swipeable area in which you can swipe up/down as well as left/right.

```
-------------------------------------------------------
|             |                          |            |
|             |                          |            |
|             |                          |            |
|             |                          |            |
|  left foot  |    up/down/left/right    | right foot |
|             |                          |            |
|             |                          |            |
|             |                          |            |
|             |                          |            |
-------------------------------------------------------
```

**Comment by owenhindley** [comment]
Added remote device control with commit 5d9e835d868c429cc61dc4c3258c6ffa5df0de7f

Instructions for use:
1. Start local node server with grunt in webdemo-server folder
2. Start local webserver with grunt in webdemo-app folder
3. Visit 127.0.0.1:8081 in desktop browser
4. Find local IP of desktop machine
5. With phone on same network, visit xxx.xxx.xxx.xxx:8081/mobile.html in Mobile Safari (iOS only for now)
6. Works best if you save this page to the Home Screen, then re-open it - will run fullscreen in landscape mode
7. Look by pressing in 'eye' area
8. Step forward by alternately pressing left and right foot buttons
9. Step sideways by double-tapping either left or right foot buttons.
