### ISSUE TITLE
Send information on player's position to Pd

### ISSUE THREAD

**Issue by ylevtov** [reactify/3DTI-binaural-web-demo#3]
Three floats:
- pos x (0.0-31.99)
- pos y (0.0-31.99)
- orientation (0.0º-359.99º)

**Comment by owenhindley** [comment]
Now sending orientation to pd under 'listener-direction'. 0 is 'North' as per map. Pos sent under 'listener-x/y'. Closed with commit 6287cd3e50d35fcb23d53e768cf4885f88d2dc0b
