### ISSUE TITLE
Add basic gait animation for walking

### ISSUE THREAD

**Issue by ylevtov** [reactify/3DTI-binaural-web-demo#4]
Just make the camera bob up and down as the person is moving, and ideally send information on when a foot comes down (i.e. the lowest point in the arc) to Pd

**Comment by owenhindley** [comment]
Added with ac1f2e8708880d2a827d6512479e0c983e80cdc0

If you want to turn it off, set SWAGGER_ENABLED = false at the top of MuseumScene.coffee
