### ISSUE TITLE
Implement loading of impulse response samples into tables

### ISSUE THREAD

**Issue by ylevtov** [reactify/3DTI-binaural-web-demo#6]
No callback necessary:
https://github.com/reactify/3DTI-binaural-web-demo/blob/master/pd/web/index.html#L64
https://github.com/reactify/3DTI-binaural-web-demo/blob/master/pd/web/index.html#L111

**Comment by owenhindley** [comment]
Made a change in 12f9baf6143d90d2991d4d12f10f5d013ee3a316, if you fire off the 'js-soundfiler:' message with the arguments as you have them in your example code, it should load the IR file from the folder shown here:
https://github.com/reactify/3DTI-binaural-web-demo/blob/master/webdemo-app/src/app/app.coffee#L103
Shout if it doesn't :)
